# fly.toml file generated for protohackers-in-elixir on 2022-12-30T16:09:40+01:00

app = "protohackers-in-elixir"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]
LOG_LEVEL = "info"
TCP_PORT = "5000"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 5000
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5000

[services.concurrency]
hard_limit = 250
soft_limit = 200
type = "connections"
