# fly.toml file generated for protohackers-in-elixir on 2022-12-30T16:09:40+01:00

app = "protohackers-in-elixir"
kill_signal = "SIGTERM"
kill_timeout = 5
processes = []

[env]

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 5001
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5001

[[services]]
internal_port = 5002
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5002

[[services]]
internal_port = 5003
protocol = "tcp"

[[services.ports]]
handlers = []
port = 5003

[services.concurrency]
hard_limit = 25
soft_limit = 20
type = "connections"
